# Generated by Django 5.2.5 on 2025-12-18 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('IdAreaC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('claveDivision', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Calle', models.CharField(max_length=100, null=True)),
                ('Col', models.CharField(max_length=100, null=True)),
                ('Ciudad', models.CharField(max_length=100, null=True)),
                ('NumExt', models.CharField(max_length=10, null=True)),
                ('CodigoP', models.CharField(max_length=10, null=True)),
                ('correo_administrador', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(db_column='contraseña_administrador', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('idPe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.areaconocimiento')),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.division')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('CedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('GradoAcademico', models.CharField(max_length=50)),
                ('EstadoCivil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')], max_length=30)),
                ('Sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('Residencia', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Colonia', models.CharField(max_length=100)),
                ('Discapacidad', models.CharField(max_length=50, null=True)),
                ('claveDocente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Puesto', models.CharField(max_length=50)),
                ('Perfil', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Asignatura', 'Por Asignatura')], max_length=50)),
                ('FechaIngreso', models.DateField()),
                ('OtroEmpleo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('categoria', models.CharField(max_length=10, null=True)),
                ('base', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('tutorado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True)),
                ('fechaInactividad', models.DateField(blank=True, null=True)),
                ('tipoInactividad', models.CharField(blank=True, null=True)),
                ('correoInstitucional', models.EmailField(max_length=100, unique=True)),
                ('correoPersonal', models.EmailField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cuentaTeams', models.CharField(blank=True, max_length=100, null=True)),
                ('areaC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.areaconocimiento')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.division')),
                ('programaE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='Promep',
            fields=[
                ('id_promep', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('ID_Compuesto', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('IdProyecto_Base', models.CharField(max_length=50, verbose_name='ID Proyecto Base')),
                ('Nombre', models.CharField(max_length=256)),
                ('Descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('Colaboradores', models.ManyToManyField(related_name='proyectos_colaborados', to='appDocentes.docente', verbose_name='Colaboradores (Docentes)')),
                ('claveDocente', models.ForeignKey(db_column='claveDocente', on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente', verbose_name='Docente Líder')),
            ],
        ),
        migrations.CreateModel(
            name='SEI',
            fields=[
                ('id_sei', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
    ]
