<<<<<<< HEAD
# Generated by Django 6.0.2 on 2026-03-02 19:40
=======
# Generated by Django 5.2.5 on 2025-12-18 14:25
>>>>>>> backend

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('IdAreaC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
<<<<<<< HEAD
                ('claveDivision', models.CharField(max_length=10, primary_key=True, serialize=False)),
=======
                ('claveDivision', models.CharField(max_length=100, primary_key=True, serialize=False)),
>>>>>>> backend
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Calle', models.CharField(max_length=100, null=True)),
                ('Col', models.CharField(max_length=100, null=True)),
                ('Ciudad', models.CharField(max_length=100, null=True)),
                ('NumExt', models.CharField(max_length=10, null=True)),
                ('CodigoP', models.CharField(max_length=10, null=True)),
<<<<<<< HEAD
=======
                ('correo_administrador', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('password', models.CharField(db_column='contraseña_administrador', max_length=128)),
>>>>>>> backend
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('idPe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('CedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('GradoAcademico', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=100)),
                ('EstadoCivil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero'), ('Divorciado', 'Divorciado'), ('Viudo', 'Viudo')], max_length=30)),
                ('Sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('Residencia', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Colonia', models.CharField(max_length=100)),
                ('Discapacidad', models.CharField(choices=[('Visual', 'Visual'), ('Auditiva', 'Auditiva'), ('Fisica', 'Fisica'), ('Mental', 'Mental'), ('Otra', 'Otra'), ('Ninguna', 'Ninguna')], max_length=50, null=True)),
                ('claveDocente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Puesto', models.CharField(choices=[('Docencia', 'Docencia'), ('Administrativo', 'Administrativo'), ('Intendencia', 'Intendencia')], max_length=50)),
                ('Perfil', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Asignatura', 'Por Asignatura')], max_length=50)),
                ('FechaIngreso', models.DateField()),
                ('OtroEmpleo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('categoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=10, null=True)),
                ('base', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=20, null=True)),
                ('tutorado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True)),
                ('FechaInactividad', models.DateField(blank=True, null=True, verbose_name='Fecha de Inactividad')),
                ('TipoInactividad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de Inactividad')),
                ('SEI_Nivel', models.CharField(blank=True, choices=[('Nivel 1', 'Nivel 1'), ('Nivel 2', 'Nivel 2'), ('Nivel 3', 'Nivel 3'), ('Candidato', 'Candidato')], max_length=50, null=True, verbose_name='Nivel SEI')),
                ('correoInstitucional', models.EmailField(max_length=100, unique=True)),
                ('correoPersonal', models.EmailField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cuentaTeams', models.CharField(blank=True, max_length=100, null=True)),
                ('areaC', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.areaconocimiento')),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.division')),
                ('programaE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Proyectos',
            fields=[
                ('IdProyecto_Base', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Proyecto Base')),
=======
            name='Docente',
            fields=[
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('CedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('GradoAcademico', models.CharField(max_length=50)),
                ('EstadoCivil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')], max_length=30)),
                ('Sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('Residencia', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Colonia', models.CharField(max_length=100)),
                ('Discapacidad', models.CharField(max_length=50, null=True)),
                ('claveDocente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Puesto', models.CharField(max_length=50)),
                ('Perfil', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Asignatura', 'Por Asignatura')], max_length=50)),
                ('FechaIngreso', models.DateField()),
                ('OtroEmpleo', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2)),
                ('categoria', models.CharField(max_length=10, null=True)),
                ('base', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('tutorado', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True)),
                ('fechaInactividad', models.DateField(blank=True, null=True)),
                ('tipoInactividad', models.CharField(blank=True, null=True)),
                ('correoInstitucional', models.EmailField(max_length=100, unique=True)),
                ('correoPersonal', models.EmailField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('cuentaTeams', models.CharField(blank=True, max_length=100, null=True)),
                ('areaC', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.areaconocimiento')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.division')),
                ('programaE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='Promep',
            fields=[
                ('id_promep', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('ID_Compuesto', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('IdProyecto_Base', models.CharField(max_length=50, verbose_name='ID Proyecto Base')),
>>>>>>> backend
                ('Nombre', models.CharField(max_length=256)),
                ('Descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto')),
                ('Colaboradores', models.ManyToManyField(related_name='proyectos_colaborados', to='appDocentes.docente', verbose_name='Colaboradores (Docentes)')),
                ('claveDocente', models.ForeignKey(db_column='claveDocente', on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente', verbose_name='Docente Líder')),
            ],
        ),
        migrations.CreateModel(
<<<<<<< HEAD
            name='Cedulas',
            fields=[
                ('id_cedula', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Número de Cédula')),
                ('NombreTitulo', models.CharField(max_length=200, verbose_name='Nombre del Título/Grado')),
                ('Institucion', models.CharField(max_length=250, verbose_name='Institución')),
                ('FechaObtencion', models.DateField(verbose_name='Fecha de Obtención')),
                ('claveDocente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cedulas_obtenidas', to='appDocentes.docente', verbose_name='Docente Asociado')),
=======
            name='SEI',
            fields=[
                ('id_sei', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
>>>>>>> backend
            ],
            options={
                'verbose_name': 'Cédula Profesional',
                'verbose_name_plural': 'Cédulas Profesionales',
                'unique_together': {('id_cedula', 'claveDocente')},
            },
        ),
    ]
