# Generated by Django 5.2.5 on 2025-09-07 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('id_area', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('clave_division', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('num_ext', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('id_pe', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.areaconocimiento')),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.division')),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('clave_docente', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('puesto', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
                ('correo_institucional', models.EmailField(max_length=254)),
                ('correo_personal', models.EmailField(max_length=254)),
                ('correo_teams', models.EmailField(max_length=254)),
                ('base', models.CharField(max_length=10)),
                ('celular', models.CharField(max_length=15)),
                ('status_docencia', models.CharField(max_length=50)),
                ('tipo_inactividad', models.CharField(max_length=50)),
                ('discapacidad', models.BooleanField(default=False)),
                ('tutorado', models.BooleanField(default=False)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_nacimiento', models.DateField()),
                ('grado_actual', models.CharField(max_length=50)),
                ('otro_empleo', models.BooleanField(default=False)),
                ('residencia', models.CharField(max_length=100)),
                ('id_area_conocimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.areaconocimiento')),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.division')),
                ('id_programa_educativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.programaeducativo')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaMaestria',
            fields=[
                ('num_ced_m', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaLicenciatura',
            fields=[
                ('num_ced_lic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaDoctorado',
            fields=[
                ('num_ced_dr', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='Promep',
            fields=[
                ('id_promep', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('id_proyecto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
        migrations.CreateModel(
            name='SEI',
            fields=[
                ('id_sei', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.profesor')),
            ],
        ),
    ]
