# Generated by Django 5.2.5 on 2025-11-16 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectoinvestigacion',
            old_name='IdProyecto',
            new_name='IdProyecto_Base',
        ),
        migrations.AlterField(
            model_name='docente',
            name='GradoAcademico',
            field=models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=100),
        ),
        migrations.AlterField(
            model_name='proyectoinvestigacion',
            name='Nombre',
            field=models.CharField(max_length=256),
        ),
    ]
