# Generated by Django 5.2.5 on 2025-10-10 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura',
            name='id_area',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id_area_conocimiento',
        ),
        migrations.RemoveField(
            model_name='asignatura',
            name='id_division',
        ),
        migrations.RemoveField(
            model_name='ceduladoctorado',
            name='clave_docente',
        ),
        migrations.RemoveField(
            model_name='cedulalicenciatura',
            name='clave_docente',
        ),
        migrations.RemoveField(
            model_name='cedulamaestria',
            name='clave_docente',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id_division',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='id_programa_educativo',
        ),
        migrations.RemoveField(
            model_name='promep',
            name='clave_docente',
        ),
        migrations.RemoveField(
            model_name='sei',
            name='clave_docente',
        ),
        migrations.RemoveField(
            model_name='proyectoinvestigacion',
            name='clave_docente',
        ),
        migrations.DeleteModel(
            name='AreaConocimiento',
        ),
        migrations.DeleteModel(
            name='Asignatura',
        ),
        migrations.DeleteModel(
            name='CedulaDoctorado',
        ),
        migrations.DeleteModel(
            name='CedulaLicenciatura',
        ),
        migrations.DeleteModel(
            name='CedulaMaestria',
        ),
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.DeleteModel(
            name='ProgramaEducativo',
        ),
        migrations.DeleteModel(
            name='Promep',
        ),
        migrations.DeleteModel(
            name='SEI',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
        migrations.DeleteModel(
            name='ProyectoInvestigacion',
        ),
    ]
