# Generated by Django 5.2.5 on 2026-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='claveDivision',
            field=models.CharField(db_column='claveDivision', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='division',
            name='correo_administrador',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
