# Generated by Django 5.2.5 on 2025-10-10 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appDocentes', '0002_remove_asignatura_id_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('Nombre', models.CharField(max_length=100)),
                ('ApellidoP', models.CharField(max_length=100)),
                ('ApellidoM', models.CharField(max_length=100)),
                ('FechaNacimiento', models.DateField()),
                ('CedulaProfesional', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('GradoAcademico', models.CharField(max_length=50)),
                ('EstadoCivil', models.CharField(choices=[('Casado', 'Casado'), ('Soltero', 'Soltero')], max_length=30)),
                ('Sexo', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer')], max_length=10)),
                ('Residencia', models.CharField(max_length=100)),
                ('Ciudad', models.CharField(max_length=100)),
                ('Colonia', models.CharField(max_length=100)),
                ('claveDocente', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Puesto', models.CharField(max_length=50)),
                ('idDivision_FK', models.CharField(choices=[('H', 'Hombre'), ('M', 'Mujer')], max_length=1)),
                ('Perfil', models.CharField(choices=[('Tiempo Completo', 'Tiempo Completo'), ('Medio Tiempo', 'Medio Tiempo'), ('Por Asignatura', 'Por Asignatura')], max_length=50)),
                ('FechaIngreso', models.DateField()),
                ('correoInstitucional', models.EmailField(max_length=100, unique=True)),
                ('correoPersonal', models.EmailField(blank=True, max_length=100, null=True)),
                ('Telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
