# Generated by Django 5.2.5 on 2025-11-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0002_rename_idproyecto_proyectoinvestigacion_idproyecto_base_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProyectoInvestigacion',
            new_name='Proyecto',
        ),
    ]
