# Generated by Django 5.2.5 on 2025-11-16 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0003_rename_proyectoinvestigacion_proyecto'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Proyecto',
            new_name='Proyectos',
        ),
    ]
