# Generated by Django 5.2.5 on 2025-10-10 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='idDivision_FK',
            field=models.CharField(choices=[('DACyTI', 'DACyTI'), ('DAIA', 'DAIA'), ('DACB', 'DACB')], max_length=10),
        ),
    ]
