# Generated by Django 5.2.5 on 2025-10-11 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0004_alter_docente_iddivision_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='Discapacidad',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
        migrations.AddField(
            model_name='docente',
            name='OtroEmpleo',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2),
        ),
    ]
