# Generated by Django 5.2.5 on 2025-12-08 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0004_rename_proyecto_proyectos'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='Colaboradores',
            field=models.ManyToManyField(related_name='proyectos_colaborados', to='appDocentes.docente', verbose_name='Colaboradores (Docentes)'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='Descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción del Proyecto'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='claveDocente',
            field=models.ForeignKey(db_column='claveDocente', on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente', verbose_name='Docente Líder'),
        ),
    ]
