# Generated by Django 5.2.5 on 2025-10-11 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0005_docente_discapacidad_docente_otroempleo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('claveDivision', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100, null=True)),
                ('Calle', models.CharField(max_length=100, null=True)),
                ('Col', models.CharField(max_length=100, null=True)),
                ('Ciudad', models.CharField(max_length=100, null=True)),
                ('NumExt', models.CharField(max_length=10, null=True)),
                ('CodigoP', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='docente',
            name='idDivision_FK',
        ),
        migrations.AddField(
            model_name='docente',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.division'),
        ),
    ]
