# Generated by Django 5.2.5 on 2025-10-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0006_division_remove_docente_iddivision_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Discapacidad',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
