# Generated by Django 5.2.5 on 2025-10-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0007_alter_docente_discapacidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='Discapacidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
