# Generated by Django 5.2.5 on 2025-10-18 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0008_alter_docente_discapacidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaConocimiento',
            fields=[
                ('IdAreaC', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramaEducativo',
            fields=[
                ('IdPEd', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='docente',
            name='base',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='categoria',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='cuentaTeams',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='tutorado',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No')], default='No', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='areaC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.areaconocimiento'),
        ),
        migrations.AddField(
            model_name='docente',
            name='programaE',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.programaeducativo'),
        ),
    ]
