# Generated by Django 5.2.5 on 2025-10-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0009_areaconocimiento_programaeducativo_docente_base_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaeducativo',
            old_name='IdPEd',
            new_name='IdPE',
        ),
    ]
