# Generated by Django 5.2.5 on 2025-10-18 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0010_rename_idped_programaeducativo_idpe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programaeducativo',
            old_name='IdPE',
            new_name='idPe',
        ),
    ]
