# Generated by Django 5.2.6 on 2025-11-16 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0011_rename_idpe_programaeducativo_idpe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('clave_asignatura', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('id_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.areaconocimiento')),
                ('id_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.division')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaDoctorado',
            fields=[
                ('num_ced_dr', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaLicenciatura',
            fields=[
                ('num_ced_lic', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='CedulaMaestria',
            fields=[
                ('num_ced_m', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('institucion', models.CharField(max_length=100)),
                ('fecha_obtencion', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='Promep',
            fields=[
                ('id_promep', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='ProyectoInvestigacion',
            fields=[
                ('id_proyecto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
        migrations.CreateModel(
            name='SEI',
            fields=[
                ('id_sei', models.IntegerField(primary_key=True, serialize=False)),
                ('superfave', models.CharField(max_length=50)),
                ('nivel', models.CharField(max_length=50)),
                ('clave_docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appDocentes.docente')),
            ],
        ),
    ]
