# Generated by Django 5.2.6 on 2025-11-16 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0012_asignatura_ceduladoctorado_cedulalicenciatura_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='fechaInactividad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='tipoInactividad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
