# Generated by Django 5.2.6 on 2025-11-29 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDocentes', '0013_docente_fechainactividad_docente_tipoinactividad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyectoinvestigacion',
            old_name='superfave',
            new_name='superllave',
        ),
        migrations.AddField(
            model_name='proyectoinvestigacion',
            name='colaboradores',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proyectoinvestigacion',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='areaC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.areaconocimiento'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.division'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='programaE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='appDocentes.programaeducativo'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='tipoInactividad',
            field=models.CharField(blank=True, null=True),
        ),
    ]
